version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 100
  method-count:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 15
  return-statements:
    config:
      threshold: 50
exclude_patterns:
- "**/*.js"
- "**/*.html"
- "**/*.json"
