image: gitpod/workspace-full-vnc

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

tasks:
  - init: pyenv install 3.5.0
    command: pyenv local 3.5.0;pip3 install -r requirements.txt
