language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pandas
  - pip install xlrd
  - pip install matplotlib
    #For Coverage Report
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pwd
  - cd Function
  #- python Generating_Test_Case.py
  #- for dir in /home/travis/build/prithvisekhar/VehicalDiagnosticAlgo/Function/*/; do cd $dir; python Test_*.py; coverage run Test_*.py; coverage html;cd .. ; done
  - ls
  - while read p; do  echo $p;cd $p;ls ;cd .. ; done <Running_Pipline.csv
  - pwd
  - echo "Done Done"
  

 # - coverage run 1.py
branches:
  only:
   - master
after_success:
#    - coveralls
#    - codecov
    


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
    
after_deploy:
  - git add Testing
  - git commit -m "Updating Execution"
  - git push

    


    
notifications:
  email:
    recipients:
   #   - prithvisekhp@xxx.com #default sends to registered email
    on_success: always
    on_failure: always
